Update build.yml
Added test report collection and disable test execution during deployment

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,9 +29,14 @@ jobs:
         cache: maven
     - name: Build with Maven
       run: ./mvnw -B clean verify --file pom.xml
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v5
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/build/test-results/test/TEST-*.xml'
     - name: Verify index generation
       run: echo $(git diff -- sysml.library/.index.json) | grep -e '^$' || (echo "Library index in the git repository is not up to date. Please re-generate it and push changes to the repository."; exit 1)
     - name: Publish to Github Packages
-      run: ./mvnw -B deploy
+      run: ./mvnw -B deploy -DskipTests=true
       env:
         GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
